export const CHOOSE_PERSON = 'CHOOSE_PERSON';
export const DROP_PERSON = 'DROP_PERSON';
export const LOAD_SELECTIONS = 'LOAD_SELECTIONS';
export const SUBMIT_BOARD = 'SUBMIT_BOARD';
export const CLEAR_BOARD = 'CLEAR_BOARD';
export const LOAD_CATEGORY = 'LOAD_CATEGORY';
